defaults:
  - files: iris
  - paths: paths
  - runparams: runparams
  - knnparams: knnparams
  - credentials: credentials

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


